#!/bin/sh
set -e

EXTENSION_TARGET="/usr/share/nautilus-python/extensions/folder-color.py"

case "$1" in
    remove|deconfigure|upgrade|failed-upgrade)
        rm -f "$EXTENSION_TARGET"
        ;;
esac

exit 0
